"""
Django settings for AutoOrder project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8h%8t-x7i%gdr%td$0!^$p!y%h^ibfgnxvt%&#%287%*5@)28q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    "userhome.apps.userhomeConfig",
    "superuserhome.apps.superuserhomeConfig",
    "login.apps.loginConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# mail(gmailの使用を想定）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587 # gmail

# user.txtから読み込んだ設定を使って変数にセット(user.txtはbd.sqliteと同じフォルダに置き，コミットしないでください)
'''
---user.txt---
your_gmail@gmail（送信元メールアドレスになります）
your_passward（16文字のアプリパスワード)
------
アプリパスワードについて参考文献 https://www.bing.com/ck/a?!&&p=cb32ea67cde15b3dJmltdHM9MTcwMzAzMDQwMCZpZ3VpZD0zNjAyMzAwYi1mZTcxLTYxZTgtMzdhZi0yMzlkZmY5YjYwODYmaW5zaWQ9NTIwNA&ptn=3&ver=2&hsh=3&fclid=3602300b-fe71-61e8-37af-239dff9b6086&psq=ttps%3a%2f%2fcodelab.website%2fdjango-send-gmail%2f%23%3a%7e%3atext%3d%255BDjango%255DGmail%2520%e3%81%ae%e3%83%a1%e3%83%bc%e3%83%ab%e3%82%a2%e3%83%89%e3%83%ac%e3%82%b9%e3%81%8b%e3%82%89%e3%83%a1%e3%83%bc%e3%83%ab%e3%82%92%e9%80%81%e4%bf%a1%e3%81%a7%e3%81%8d%e3%82%8b%e3%82%88%e3%81%86%e3%81%ab%e3%81%99%e3%82%8b%25201%2520%e5%89%8d%e6%8f%90%e6%9d%a1%e4%bb%b6%2520Python%2520%253A%25203.9.1%2520...%2cGmail%2520%e3%81%ab%e3%83%ad%e3%82%b0%e3%82%a4%e3%83%b3%e3%81%97%e3%81%be%e3%81%99%e3%80%82%2520...%25205%2520E%2520%e3%83%a1%e3%83%bc%e3%83%ab%e8%a8%ad%e5%ae%9a%2520...%2520%e3%81%9d%e3%81%ae%e4%bb%96%e3%81%ae%e3%82%a2%e3%82%a4%e3%83%86%e3%83%a0&u=a1aHR0cHM6Ly9jb2RlbGFiLndlYnNpdGUvZGphbmdvLXNlbmQtZ21haWwv&ntb=1
'''
with open(BASE_DIR /'user.txt','r') as f:
    datalist = f.readlines()
# 送信元メールアドレス
EMAIL_HOST_USER = datalist[0]
EMAIL_HOST_PASSWORD = datalist[1]
EMAIL_USE_TLS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AutoOrder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR /'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AutoOrder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    BASE_DIR / 'static',
    )

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
